### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by CuiTianci** [guolindev/giffun#14]
ModifyUserInfoActivity，问题不是出现在该文件中的代码（具体位置我没找到），点击该页面的昵称EditText，程序崩溃，闪退。手机：Google Nexus API26。

**Comment by MrTaoGe** [comment]
目前只有这个机子出问题吗？最好是连接上pc，然后看一下崩溃日志。既然有崩溃闪退，应该能打印出崩溃日志。

**Comment by CuiTianci** [comment]
由于特殊原因，只能用该虚拟机进行测试，崩溃日志如下：
2019-01-29 13:49:35.242 13581-13581/com.quxianggif.opensource E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.quxianggif.opensource, PID: 13581
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getBoundsOnScreen(android.graphics.Rect)' on a null object reference
        at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:484)
        at android.app.assist.AssistStructure.<init>(AssistStructure.java:1908)
        at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3035)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1807)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by MrTaoGe** [comment]
①https://stackoverflow.com/questions/45840856/android-8-0-oreo-crash-on-focusing-textinputedittext
②https://stackoverflow.com/questions/45898228/android-attempt-to-invoke-virtual-method-void-android-view-view-getboundsonsc

上面两篇文章也许能解决你的问题，看起来问题应该出现在TextInputLayout这个布局控件上，它的使用有一些必须要注意的问题。
