### ISSUE TITLE
换头像、主页背景调用相机出错  

### ISSUE THREAD

**Issue by 985211yyg** [guolindev/giffun#17]
机型：pixel xl 系统版本：9.0  
================
2019-01-29 10:57:51.587 3986-3986/com.quxianggif.opensource E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.quxianggif.opensource, PID: 3986
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:604)
        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:578)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:416)
        at com.quxianggif.user.ui.ModifyUserInfoActivity.takePhoto(ModifyUserInfoActivity.kt:464)
        at com.quxianggif.user.ui.ModifyUserInfoActivity.access$takePhoto(ModifyUserInfoActivity.kt:73)
        at com.quxianggif.user.ui.ModifyUserInfoActivity$showTakePictureDialog$1.onClick(ModifyUserInfoActivity.kt:435)
        at android.support.v7.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1067)
        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1159)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
        at android.widget.AbsListView$3.run(AbsListView.java:4052)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by yangzai100** [comment]
- _### **机型：一加6t     系统版本：9.0**_

java.lang.SecurityException: UID 10117 does not have permission to content://com.quxianggif.fileprovider/my_images/Android/data/com.quxianggif.opensource/cache/taken_photo.jpg [user 0]
        at android.os.Parcel.createException(Parcel.java:1950)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3703)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1856)
        at android.app.Activity.startActivityForResult(Activity.java:4599)
        at 

- 

- [ ] android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)

        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
        at android.app.Activity.startActivityForResult(Activity.java:4557)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
        at com.quxianggif.user.ui.ModifyUserInfoActivity.takePhoto(ModifyUserInfoActivity.kt:471)
        at com.quxianggif.user.ui.ModifyUserInfoActivity.access$takePhoto(ModifyUserInfoActivity.kt:73)
        at com.quxianggif.user.ui.ModifyUserInfoActivity$showTakePictureDialog$1.onClick(ModifyUserInfoActivity.kt:435)
        at android.support.v7.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1067)
        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1201)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3178)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.checkGrantUriPermissionLocked(ActivityManagerService.java:11278)
        at com.android.server.am.ActivityManagerService.checkGrantUriPermissionFromIntentLocked(ActivityManagerService.java:11442)
        at com.android.server.am.ActivityManagerService.grantUriPermissionFromIntentLocked(ActivityManagerService.java:11484)
        at com.android.server.am.ActivityStarter.startActivityUnchecked(ActivityStarter.java:1587)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:1351)

**Comment by MrTaoGe** [comment]
@985211yygg 你的这个问题应该是在<b>ModifyUserInfoActivity.kt</b>这个文件的464行(错误信息中写了)，
其中<b>authority</b>这个参数的值必须要和清单文件AndroidManifest.xml中给&quot;provider&quot;配置的authorities属性值保持一致，代码中应该是少写了一个&quot;opensource&quot;，完整的写法应该是"com.quxianggif.opensource.fileprovider"

**Comment by MrTaoGe** [comment]
@yangzai100 产生你这个问题的原因应该和上面是一样的，报错的信息不太相同，归根结底是android6.0以后使用系统相册的权限问题，这里在使用FileProvider的时候写错了authority的路径，和AndroidManifest.xml中的authorities值不一样，应该两者保持一致。

**Comment by tianshaokai** [comment]
oppo 换头像闪退

**Comment by guolindev** [comment]
已修复 
https://github.com/guolindev/giffun/commit/a50f0615f1dd1e54d20b9e506fa43c9525c7f410
